theme: jekyll-theme-slate
title: Zhun's Archive
author: Zhun Cheng

navigation:
  - title: Personal
    url: /personal/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/
